name: MacOS
on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "0 12 * * *"

env:
  BASE_BRANCH: master
  SCONS_CACHE_LIMIT: 7168

jobs:
  macos-templates:
    runs-on: "macos-latest"

    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: MacOS Template Debug
            cache-name: macos-template-debug
            target: template_debug

          - name: MacOS Template Release
            cache-name: macos-template-release
            target: template_release

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: master

      - name: Checkout LuaAPI
        uses: actions/checkout@v3
        with:
          repository: WeaselGames/godot_luaAPI
          ref: main
          submodules: recursive
          path: modules/luaAPI

      - name: Checkout Voxel
        uses: actions/checkout@v3
        with:
          repository: Zylann/godot_voxel
          ref: master
          path: modules/voxel

      - name: Checkout GodotSteam
        uses: actions/checkout@v3
        with:
          repository: Gramps/GodotSteam
          ref: godot4
          path: modules/godotsteam

      - name: Delete SDK Folder
        run: |
          rm -rf modules/godotsteam/sdk

      - name: Checkout SteamWorks SDK
        uses: actions/checkout@v3
        with:
          lfs: "true"
          repository: ${{ secrets.steamworks_sdk_repo }}
          ref: master
          token: ${{ secrets.steamworks_sdk_repo_token }}
          path: modules/godotsteam/sdk

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh

      - name: Load .scons_cache directory
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{matrix.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{matrix.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{matrix.cache-name}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{matrix.cache-name}}-${{env.BASE_BRANCH}}

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version

      - name: Compilation
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
          BUILD_NAME: "SP"
        run: |
          scons platform=macos target=${{ matrix.target }} extra_suffix=SP

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.cache-name}}
          path: bin
