name: MacOS
on:
  workflow_dispatch:
  
  push:
    branches:
      - "master"
     paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "0 12 * * *"

env:
  BASE_BRANCH: master
  SCONS_CACHE_LIMIT: 7168

jobs:
  macos-Templates:
    runs-on: "macos-latest"

    name: MacOS Templates

    steps:
      - name: Checkout Godot
        uses: actions/checkout@v3
        with:
          repository: godotengine/godot
          ref: master
      - name: Checkout LuaAPI
        uses: actions/checkout@v3
        with:
          repository: WeaselGames/godot_luaAPI
          ref: main
          submodules: recursive
          path: modules/luaAPI
      - name: Checkout Voxel
        uses: actions/checkout@v3
        with:
          repository: Zylann/godot_voxel
          ref: master
          path: modules/voxel
      - name: Checkout GodotSteam
        uses: actions/checkout@v3
        with:
          repository: Gramps/GodotSteam
          ref: master
          path: modules/godotsteam

      - name: Delete SDK Folder
        run: |
          rm -rf modules/godotsteam/sdk

      - name: Checkout SteamWorks SDK
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.steamworks_sdk_repo }}
          ref: master
          token: ${{ secrets.steamworks_sdk_repo_token }}
          path: modules/godotsteam/sdk

      - name: Setup Vulkan SDK
        run: |
          sh misc/scripts/install_vulkan_sdk_macos.sh
      - name: Load .scons_cache directory
        id: macos-templates-cache
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/.scons_cache/
          key: ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
          restore-keys: |
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}-${{github.sha}}
            ${{github.job}}-${{env.BASE_BRANCH}}-${{github.ref}}
            ${{github.job}}-${{env.BASE_BRANCH}}
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Configuring Python packages
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install scons
          python --version
          scons --version
      - name: Compilation
        working-directory: ./scripts
        env:
          SCONS_CACHE: ${{github.workspace}}/.scons_cache/
          BUILD_NAME: 'SP'
        run: |
          scons platform=macos target=template_debug extra_suffix=SP
          scons platform=macos target=template_release extra_suffix=SP
      - name: Prepare artifact
        run: |
          strip scripts/godot/bin/godot.*
          chmod +x scripts/godot/bin/godot.*
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.job}}
          path: scripts/godot/bin